#!/bin/sh
set -e

url="https://raw.githubusercontent.com/webuni/shell-task-runner/master/runner"
[ -f ./.runner ] && [ .runner -nt "$0" ] || wget -q "$url" -O- > .runner || curl -fso .runner "$url"
. ./.runner

if [ -r $(pwd)'/.env' ]; then
    . $(pwd)'/.env'
fi

IMAGE_NAMESPACE="${IMAGE_NAMESPACE:-minidocks webuni}"
GIT_NAMESPACE="${GIT_NAMESPACE:-minidocks}"
HUB_NAMESPACE="${HUB_NAMESPACE:-minidocks webuni}"
HUB_URL=https://cloud.docker.com/v2
HUB_API_URL=https://cloud.docker.com/api/build/v1

to_json(){
    printf '{"%s"}' "$(echo "$1" | sed -E 's/\\/\\\\/g; s/"/\\"/g; s/=/": "/g; s/&/", "/g; s/"(true|false)"/\1/g')"
}

json_escape()(
    printf "%s" "$1" | sed 's/"/\\"/g'
)

http_code(){
    printf "%s" "$1" | head -n1 | cut -d" " -f2
}

http_body(){
    printf "%s" "$1" | sed '1,/^$/d'
}

assert_http_code(){
    if [ "$(http_code "$1")" != "$2" ]; then
        printf "\033[30;41m%s\033[0m\n" "$1" >&2
        exit 1
    fi
}

query()(
    json="$1"
    shift
    printf '%s' "$json" | _docker_run minidocks/curl jq "$@"
)

do_request(){
    _docker_run minidocks/curl \
        curl --retry 5 --retry-delay 3 -H "Content-Type: application/json" -H "Accept: application/json" -i -s "$@" \
    | tr -d '\r' | tr '\n' '\r' | sed -e 's/.\+\(HTTP\/1.\+\)/-\1-/' | tr '\r' '\n'
}

run_git(){
    _docker_run -e FILE_NETRC_PATH="/home/user/.netrc" -e FILE_NETRC_CONTENT="machine github.com login token password $GITHUB_TOKEN" minidocks/git git "$@"
}

github(){
    do_request -H "Authorization: token $GITHUB_TOKEN" -X "$1" --data "$3" "https://api.github.com$2"
}

travis(){
    do_request -H "Travis-API-Version: 3" -H "Authorization: token $TRAVIS_TOKEN" -X "$1" --data "$3" "https://api.travis-ci.com$2"
}

hub(){
    if [ -z "$REGISTRY_TOKEN" ] || [ $(( $(date +"%s") - REGISTRY_TOKEN_TIME )) -gt 300 ]; then
        response="$(do_request -X "POST" --data "{\"username\": \"$(json_escape "$DOCKER_LOGIN")\", \"password\": \"$(json_escape "$DOCKER_PASSWORD")\"}" "$HUB_URL/users/login/")"
        assert_http_code "$response" "200"
        REGISTRY_TOKEN="$(query "$(http_body "$response")" -r '.token')"
        REGISTRY_TOKEN_TIME="$(date +"%s")"
    fi

    do_request -H "Authorization: JWT $REGISTRY_TOKEN" -X "$1" --data "$3" "${4:-$HUB_URL}$2"
}

hub_api()(
    hub "$1" "$2" "$3" "$HUB_API_URL"
)

lsdir()(
    if [ -d "." ]; then
      find "." -mindepth 1 -maxdepth 1 -type d -not -path '*/\.*' -printf '%f\n' | sort
    fi
)

froms()(
    for namespace in $IMAGE_NAMESPACE; do
        _print "$1" | grep "FROM $namespace/" | cut -d/ -f2 | cut -d' ' -f1 | uniq
    done
)

deps()(
    dir="${1:-$(pwd)}"
    basename="$(basename "$dir")"
    froms=""

    if [ -d "$dir" ]; then
        for file in $(find "$dir" -name "Dockerfile"); do
            froms="$(froms "$(cat "$file")") $froms"
        done
    fi

    froms="$(echo "$froms" | sed -e 's/ /\n/g' | grep -v "$basename" | cut -d: -f1 | sort | uniq | xargs)"
    for from in $froms; do
        froms="$(deps "$from") $froms"
    done

    echo "$froms" | xargs
)

split()(
    name="$1"
    repo="$GIT_NAMESPACE/$1"
    url="https://github.com/$repo"
    _ansi --yellow --nl "Split $name -> $url"
    response="$(github "GET" "/repos/$repo")"
    if [ "$(http_code "$response")" = "404" ]; then
        printf 'Create git repository "%s"\n' "$repo"
        response="$(github "POST" "/orgs/$GIT_NAMESPACE/repos" "$(to_json "name=$name")")"
        assert_http_code "$response" "201"
    fi

    run_git splitsh --prefix "$name" --remote "$url" --force
)

versions()(
    if [ -f "$1/build.sh" ]; then
        "$1/build.sh" --versions
    elif [ -d "$1" ]; then
        find "$1"/* -maxdepth 0 \( -type d -o -type l \) | sort | cut -d/ -f2
    fi
)

build()(
    package="" version="" source_dir="" opts=""
    while [ -n "$1" ]; do
        case "$1" in
            --force) opts="$opts --no-cache";;
            --no-clear) no_clear="1";;
            --dir*) source_dir="$2"; shift;;
            -*) opts="$opts $1";;
            *) if [ -z "$package" ]; then package="$1"; else version="$1"; fi;;
        esac
        shift
    done

    if [ -f "$source_dir/build.sh" ]; then
        source_dir="$source_dir"
    elif [ -f "$package/build.sh" ]; then
        source_dir="$package"
    elif [ -z "$source_dir" ]; then
        source_dir="${package}/${version}"
    else
        source_dir="${source_dir}/${version}"
    fi

    if [ ! -f "$source_dir/Dockerfile" ]; then
        _ansi --bg-yellow --nl --black -f 'Skip "%s". Unable to find file "%s/Dockerfile"' "$source_dir" >&2
        return
    fi

    froms="$(froms "$(cat "$source_dir/Dockerfile")")"
    for from in $froms; do
        tag="$(echo "$from" | cut -d: -f2 -s)"
        task_build "$(echo "$from" | cut -d: -f1)" "${tag:-latest}"
    done

    target_dir="/tmp/${package}-${version}"
    if [ -f "$source_dir/build.sh" ]; then
        for namespace in $IMAGE_NAMESPACE; do
            _ansi --nl --green --format "Build %s/%s:%s - %s" "$namespace" "$package" "$version" "$source_dir"
            namespace="$namespace" docker_opts="$(echo "$opts" | xargs)" "$source_dir/build.sh" "$version"
        done
        printf "\n"
    elif [ ! -d "$target_dir" ] || [ "$no_clear" != 1 ]; then
        rm -rf "$target_dir"
        cp -rfL "$source_dir" "$target_dir"
        for namespace in $IMAGE_NAMESPACE; do
            _ansi --nl --green --format "Build %s/%s:%s - %s" "$namespace" "$package" "$version" "$source_dir"
            docker build $opts -t "$namespace/$package:$version" "$target_dir"
        done
        if [ "$no_clear" != 1 ]; then rm -rf "$target_dir"; fi
        printf "\n"
    else
        _ansi --gren --nl --format "Image %s/%s:%s exists" "$IMAGE_NAMESPACE" "$package" "$version"
    fi
)

# Build docker image
#
# Argument
# $1: Package name
# [$2: Version]
#
# Options:
# --dir
# --force
task_build()(
    package="" version="" dir="" opts=""
    while [ -n "$1" ]; do
        case "$1" in
            --dir*) dir="$2"; shift;;
            --force) opts="${opts} --no-cache";;
            -*) opts="${opts} $1";;
            *) if [ -z "$package" ]; then package="$1"; else version="$1"; fi;;
        esac
        shift
    done

    if [ "${package#*/}" != "$package" ]; then
        version="$(printf '%s' "$package" | cut -d/ -f2)"
        package="$(printf '%s' "$package" | cut -d/ -f1)"
    fi

    if [ ! -d "${dir:-$package}" ]; then
        run_git clone "https://github.com/$GIT_NAMESPACE/$package"
    fi

    versions="$(versions "${dir:-$package}")"
    if [ -n "$version" ] && echo "$versions" | grep -qx "$version"; then
        build "$package" "$version" --dir "$dir" $opts
    else
        for version in $versions; do
            build "$package" "$version" --dir "$dir" $opts
        done
    fi
)

# Split monorepository
task_split()(
    processed=" "
    for name in ${1:-$(lsdir)}; do
        for dep in $(deps "$name"); do
            if [ -z "${processed##* $dep *}" ]; then
                continue
            fi

            split "$dep"
            processed=" $dep $processed"
        done

        if [ -z "${processed##* $name *}" ]; then
            continue
        fi

        split "$name"
        processed=" $name $processed"
    done
)

# Copy environment variables to travis
task_travis__env()(
    force='' dir=''
    while [ -n "$1" ]; do
        case "$1" in
            -f|--force) force=1;;
            *) dir="$1";;
        esac
        shift
    done

    for name in ${dir:-$(lsdir)}; do
        repo="${GIT_NAMESPACE}%2F${name}"
        _ansi --yellow --nl "Sync env: $name -> https://travis-ci.com/$GIT_NAMESPACE/$name"
        response="$(travis 'GET' "/repo/${repo}/env_vars")"
        if [ "$(http_code "$response")" = "200" ]; then
            vars="$(query "$(http_body "$response")" -r '.env_vars[] | .name+":"+.id')"
            for var in REGISTRY_LOGIN REGISTRY_PASSWORD; do
                value="$(eval printf '%s' "\$$var" | sed -E 's/([$&\])/\\\1/g; s/\\/\\\\/g; s/"/\\"/g')"
                body="{\"env_var.name\": \"${var}\", \"env_var.value\": \"${value}\", \"env_var.public\": false}"
                varid="$(printf '%s' "$vars" | grep "$var" || true)"
                if [ -n "$force" ] && [ -n "$varid" ]; then
                    printf 'Update "%s" variable' "$var"
                    response="$(travis 'PATCH' "/repo/${repo}/env_var/${varid#*:}" "$body")"
                    assert_http_code "$response" "200" && _pass || _fail
                elif [ -z "$varid" ]; then
                    printf 'Copy "%s" variable' "$var"
                    response="$(travis 'POST' "/repo/${repo}/env_vars" "$body")"
                    assert_http_code "$response" "201" && _pass || _fail
                fi
            done
        else
            printf 'Repository "%s" does not exist\n' "$GIT_NAMESPACE/$name"
        fi
    done
)

# Trigger build on travis
task_travis__trigger()(
    for name in ${1:-$(lsdir)}; do
        repo="${GIT_NAMESPACE}%2F${name}"
        _ansi --yellow --nl "Build request: $name -> https://travis-ci.com/$GIT_NAMESPACE/$name"
        response="$(travis 'GET' "/repo/${repo}/builds")"
        ! state="$(query "$(http_body "$response")" -r '.builds[] | .state' | grep -E '(created|started)')"
        if [ -n "$state" ]; then
            continue
        fi

        response="$(travis 'POST' "/repo/${repo}/requests")"
        if [ "$(http_code "$response")" != "202" ]; then
            _ansi --bg-red --nl --black -f 'Error to trigger a build of "%s"' "$name"
            exit 1
        fi
    done
)

# Push docker image to https://hub.docker.com
task_push()(
    for name in ${1:-$(lsdir)}; do
        for namespace in $HUB_NAMESPACE; do
            hub_name="$namespace/$name"

            _ansi --yellow --nl "Push docker image $hub_name"

            data="$(to_json "description=Minimal $name images&namespace=$namespace&name=$name&image=$hub_name&privacy=public&is_private=false&provider=github&owner=$GIT_NAMESPACE&repository=$name&build_settings=__SETTINGS__")"
            settings="source_type=Branch&tag=latest&source_name=master&autobuild=true&nocache=true&dockerfile=Dockerfile&build_context=";
            if [ -f "$name/build.sh" ]; then settings="$settings/"; else settings="$settings/.hub"; fi
            settings="$(to_json "$settings")"
            data="$(echo "$data" | sed -e "s/\"__SETTINGS__\"/[$(echo "$settings" | sed -e 's/[\/&]/\\&/g')]/")"

            response="$(hub "GET" "/repositories/$hub_name/")"
            if [ "$(http_code "$response")" = "404" ]; then
                printf "Create automatic repository \"%s\"\n" "$hub_name"
                response="$(hub "POST" "/repositories/" "$data")"
                assert_http_code "$response" "201"
            fi

            response="$(hub_api "GET" "/$namespace/source/?image=$namespace%2F$name")"
            assert_http_code "$response" "200"
            uuid="$(query "$(http_body "$response")" -r ".objects[0].uuid")"
            printf "Update automatic repository \"%s(%s)\"\n" "$hub_name" "$uuid"
            if [ "$uuid" = "null" ]; then
                response="$(hub_api "POST" "/$namespace/source/" "$data")"
                assert_http_code "$response" "201"
            else
                response="$(hub_api "PATCH" "/$namespace/source/$uuid/" "{\"owner\":\"$GIT_NAMESPACE\",\"repository\":\"$name\",\"build_settings\":[$settings]}")"
                assert_http_code "$response" "202"
            fi

            for version in $(docker image ls --format "{{.Tag}}" "$hub_name" | grep -v 'none'); do
                printf " - $hub_name:$version\n"
                docker push "$hub_name:$version"
            done
        done
    done
)

# Build image via travis
task_travis__build()(
    docker login -u "$REGISTRY_LOGIN" -p "$REGISTRY_PASSWORD"
    TRAVIS_REPO_NAME="${TRAVIS_REPO_SLUG#*/}"
    task_build "$TRAVIS_REPO_NAME" --dir "."
    task_push "$TRAVIS_REPO_NAME"
)
