#!/usr/bin/env bash
#
# Wrapper for splitsh-lite

set -e

while [ -n "$1" ]; do
  case $1 in
    --prune) prune="1";;
    --prefix=*) prefix="${1#*=}";;
    --prefix) shift; prefix="$1";;
    --remote=*) remote="${1#*=}";;
    --remote) shift; remote="$1";;
    --name=*) name="${1#*=}";;
    --name) shift; name="$1";;
    --force) force="--force";;
    *) ;;
  esac
  shift
done

if [ -n "$remote" ]; then
  name="${name:-$(head /dev/urandom | tr -dc a-z | head -c 13)}"
  echo "Add remote $name ($remote)" >2
  git remote add "$name" "$remote"
fi

if [ -n "$prefix" ]; then
  SHA1="$(splitsh-lite --prefix="$prefix")"

  if [ -n "$name" ] && [ -n "$remote" ]; then
    CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
    echo "Push $SHA1 to $remote:$CURRENT_BRANCH" >2
    git push "$name" "$SHA1:refs/heads/$CURRENT_BRANCH" $force
  fi
fi

if [ -n "$prune" ]; then
  echo "Clean repository" >2
  [ -n "$name" ] && git remote remove "$name" || true
  git gc --prune=now
fi
